config/routes.rb
Rails.application.routes.draw do
  get :about, to: 'home#about', as: :about
  get :services, to: 'home#services', as: :services
  get :team, to: 'home#team', as: :team
  get :index, to: 'home#index'
  get :contact, to: 'home#contact', as: :contact
  post :contact_submission, to: 'home#contact_submission'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def team
  end

  def contact
  end

  def contact_submission
    if params[:message].present? || params[:name].present?
      @message = 'Your message has been sent succesfully.'
      ContactMailer.contact_notification(params).deliver_now
    else
      @message = 'Message not sent, Please add your name or message.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_body_class
    ['about', 'contact'].include?(params[:action]) ? '' : "service-single-page sub-page" 
  end

  def footer_class
    ['about', 'contact'].include?(params[:action]) ? 'padding-footer' : ''
  end

  def active_class(item)
    'active' if params[:action].to_sym == item
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_client.html.erb
<section class="client-section clients-partners">
  <div class="container">
    <div class="title-bar text-center">
      <h2 class="title">Clients And Partners</h2>
      <span class="title-border"></span>
    </div>
    <div class="row">
      <div class="col-md-12">
        <ul class="client-wrapper text-center worldwide-clients">
         <li class='client-images'>
            <%= image_tag 'worldwide9.png' %>
          </li>
          <li class='client-images'>
            <%= image_tag 'worldwide1.jpg' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide2.png' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide3.png' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide4.jpg' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide5.png' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide6.png' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide8.jpg' %>
          </li>
           <li class='client-images'>
            <%= image_tag 'worldwide7.png' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/home/_clients.html.erb
<section class="testimonial-section section-padding">
  <div class="container">
    <div class="title-bar text-center">
      <h2 class="title">Clients’ Testimonials</h2>
      <span class="title-border"></span>
    </div>
    <div class="row text-center">
      <div class="col-md-10 col-md-offset-1">
        <div id="testimonial-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#testimonial-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#testimonial-carousel" data-slide-to="1"></li>
          </ol>
          <div class="carousel-inner " role="listbox">
            <div class="item active">
              <div class="carousel-wrapper">
                <span class="caption">
                  <%= image_tag 'clients/client-asif.jpg' %>
                </span>
                <h3><a href="#">Dr. Muhammad Asif Shahzad and Dr. Bushra Asif </a></h3>
                <ul class="commend">
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                </ul>
                <p>(Lyell Mcewin Hospital, Adelaide)</p>
                <p class="text-align-justify">
Kaleem and Madeeha have been providing us with taxation and accounting services to ensure we are in compliance with the most recent tax legislation, treaties and incentives. Their expert opinion and advice reflects their wealth of knowledge and expertise in taxation services which is well researched and supported and always delivered in a timely and efficient manner. The best thing about them is the quality time they give to their clients and we can always count on them for tax advice.  
</p>
              </div>
            </div>
            <div class="item">
              <div class="carousel-wrapper">
                <span class="caption">
                  <%= image_tag 'clients/client-kashif.jpg' %>
                </span>
                <h3><a href="#">Dr Kashif B Khokhar </a></h3>
                <ul class="commend">
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                </ul>
                <p>(Royal Adelaide Hospital, Adelaide)</p>
                <p class="text-align-justify">
I was introduced to Mr Kaleem Ulah during a social gathering. I found The Kalculators highly professional and efficient, with a customised approach which is a really unique combination to find in the business environment today. I have no hesitation recommending them. Mr Kaleem runs a great business with a gracious heart, and is indeed a rare breed of an accountant.
</p>
              </div>
            </div>
           
        </div>
        </div>
        
      </div>
    </div>
  </div>
</section>

app/views/home/_network.html.erb
<section class="network-section">
  <div class="container">
    <h3>We plan to make that network secure & reliable</h3>
    <a href="#" class="btn btn-primary pull-right">Know More</a>
  </div>
</section>

app/views/home/_overlay_footer.html.erb
<section class="contact-section overlay-footer <%= footer_class %>">
<div class="contact-section-two">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-md-3">
        <div class="contact-wrapper-two">
          <h3 class='contact-adress-1'>SALISBURY</h3>
          <%= render partial: 'locations/salisbury', locals: { footer: true } %>
        </div>
      </div>
      <div class="col-sm-4 col-md-4 col-md-offset-1">
        <div class="contact-wrapper-two middle-wrapper">
          <h3 class='contact-adress-2'>BLAIR ATHOL</h3>
          <%= render partial: 'locations/prospect', locals: { footer: true } %>
        </div>
      </div>
      <div class="col-sm-4 col-md-3 col-md-offset-1">
        <div class="contact-wrapper-two">
          <h3 class='contact-adress-3'>MURRAY BRIDGE</h3>
          <%= render partial: 'locations/murray_bridge', locals: { footer: true } %>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/home/_query_contact.html.erb
<section class="query-contact-section">
  <div class="container">
    <h3>For any kind of query contact us</h3>
    <a href="#" class="btn btn-primary pull-right">Contact Us</a>
  </div>
</section>

app/views/home/_services.html.erb
<section class="call-to-action section-padding">
  <div class="container">
    <div class="title-bar text-center">
      <h2 class="title">Services We Provide</h2>
      <span class="title-border"></span>
    </div>
    <div class="action-wrapper">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="row">
            <div class="col-sm-4">
              <div class="wrapper-content text-center">
                <i class="fa fa-balance-scale" aria-hidden="true"></i>
                <h3>Taxation</h3>
                <%= link_to 'Details', services_url(type: 'taxation') %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="wrapper-content text-center">
                <i class="fa fa-database" aria-hidden="true"></i>
                <h3>Finance</h3>
                <%= link_to 'Details', services_url(type: 'finance') %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="wrapper-content text-center">
                <i class="fa fa-money" aria-hidden="true"></i>
                <h3>Superannuation</h3>
                <%= link_to 'Details', services_url(type: 'super') %>
              </div>
            </div>
          </div>
          <div class="row mt-60">
            <div class="col-sm-6">
              <div class="wrapper-content text-center">
                <i class="fa fa-suitcase" aria-hidden="true"></i>
                <h3>Payroll & Work Cover</h3>
                <%= link_to 'Details', services_url(type: 'payroll') %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="wrapper-content text-center">
                <i class="fa fa-window-restore" aria-hidden="true"></i>
                <h3>Accounting & Business Advice</h3>
                <%= link_to 'Details', services_url(type: 'software') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>
</section>

app/views/home/_slider.html.erb
<section class="slider-section">
  <div class="tp-banner-container">
    <div class="tp-banner" >
      <ul>
        <li data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-thumb="<%= image_tag 'mainimageslider.jpg' %>" data-delay="13000" data-title="We are the kalculators" >
          <%= image_tag 'mainimageslider.jpg', data: {bgposition: "top center", bgfit:"cover", bgrepeat:"no-repeat"} %>
          <div class="tp-caption large-text text-left customin customout"
              data-x="0"
              data-y="260"
              data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-speed="1800"
              data-start="500"
              data-easing="Power3.easeInOut"
              data-splitin="chars"
              data-splitout="chars"
              data-elementdelay="0.08"
              data-endelementdelay="0.08"
              data-end="8000"
              data-endspeed="500"
              style="z-index: 2;color: black;"
              > <h1>We listen, we advise. </br> We are here for you.</h1>
          </div>

          <div class="tp-caption small-text text-left customin customout rs-parallaxlevel-0"
              data-x="0" 
              data-y="550"
              data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-speed="2000"
              data-start="3300"
              data-easing="Power3.easeInOut"
              data-splitin="none"
              data-splitout="none"
              data-end="11000"
              data-endspeed="2000"
              data-linktoslide="next"
              style="z-index: 8;color: black;"> 
              Planning to prepare your tax return? Consider it done!
          </div>

          <div class="tp-caption lfb ltt"
              data-x="0"
              data-y="675"
              data-speed="1800"
              data-start="4500"
              data-easing="Power4.easeOut"
              data-splitin="none"
              data-splitout="none"
              data-elementdelay="0.01"
              data-endelementdelay="0.1"
              data-end="12000"
              data-endspeed="1800"
              data-endeasing="Power4.easeIn"
              style="z-index: 3;color: black;">
              <div class="link-button hidden-xs">
                <%= link_to 'About Us', about_url, class: 'btn btn-primary' %>
                <%= link_to 'Contact', contact_url, class: 'btn btn-default' %>
              </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</section>

app/views/home/_team_main.html.erb
<section class="consulting-section section-padding">
  <div class="container">
    <div class="title-bar text-center team-main-section">
      <h2 class="title">Our Team</h2>
      <span class="title-border"></span>
    </div>
    <div id="consulting-carousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#consulting-carousel" data-slide-to="0" class="active">
          <%= image_tag 'team/team-ks.jpg', alt:"team"  %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="1" class="">
          <%= image_tag 'team/team-ms.jpg', alt:"team"  %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="2" class="">
          <%= image_tag 'team/team-ss.jpg', alt:"team"  %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="3" class="">
           <%= image_tag 'team/team-v-s.jpg', alt:"team" %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="4" class="">
          <%= image_tag 'team/team-am-s.jpg', alt:"team" %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="5" class="">
          <%= image_tag 'team/team-ammar-s.jpg', alt:"team" %>
        </li>
        <li data-target="#consulting-carousel" data-slide-to="6" class="">
          <%= image_tag 'team/team-annayat-s.jpg', alt:"team" %>
        </li>
      </ol>
      <div class="carousel-inner text-align-justify" role="listbox">
        <div class="item active">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                 <%= image_tag 'team/team-k.jpg', alt:"team" %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Kaleem Ulah</h3>
                <span class="position">Principal and Registered Tax Agent</span>
                <p>Kaleem is one of the founding members of The Kalculators. He is known and recognised across South Australia as possessing some of the highest technical skill levels across the areas of accounting, taxation, financial planning and business analysis. </p>
                <p>
                Kaleem’s down-to-Earth, approachable and friendly personality is a winner amongst clients. With over a decade of experience in the accounting industry, he remains a valuable asset to both The Kalculators, and as well as his loyal clients.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                 <%= image_tag 'team/team-m.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Madeeha Usman</h3>
                <span class="position">Senior Consultant</span>
                <p>Madeeha is a Chartered Accountant as well as Kalculator’s Sage Champion and trainer. She has extensive experience with the renowned Big-4 firms, and retains expert status as an expert in Taxation, Auditing and Business Advisory. Madeeha has been working in the financial services industry for several years and is the Head of Kalculator’s Salisbury Office.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                <%= image_tag 'team/team-s.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Saki Jameson</h3>
                <span class="position">Tax Specialist</span>
                <p>Saki is an experienced Tax Specialist and his friendly and efficient work ethic ensures strong client relationships and high quality professional service for our clients.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                <%= image_tag 'team/team-v.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Jiawei Wu (Vincent)</h3>
                <span class="position">Tax Accountant</span>
                <p>Vincent is one of our delightful and hard-working graduate accountants. Having completed his degree, he is on the road to commence the Chartered Accounting Program in 2017.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                <%= image_tag 'team/team-am.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Sahar Amin</h3>
                <span class="position">Marketing Manager</span>
                <p>Sahar is the Marketing and PR Coordinator at The Kalculators, and holds experience in client relations, marketing campaigns and crisis management.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                <%= image_tag 'team/team-ammar.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Muhammad Ammar</h3>
                <span class="position">Graduate Accountant</span>
                <p>Ammar is a Certified Accounting Technician and has recently joined our team as an Accounts Assistant in the Salisbury office. He is currently working towards his Bachelors degree and is meticulously making a mark in the firm.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="row">
            <div class="col-sm-5">
              <span class="consulting-caption">
                <%= image_tag 'team/team-annayat.jpg', alt:"team"  %>
              </span>
            </div>
            <div class="col-sm-7">
              <div class="content-wrapper">
                <h3>Hafiz Anayat Ullah</h3>
                <span class="position">Graduate Accountant</span>
                <p>Hafiz is a consummate professional and upholds the standard of The Kalculators to provide outstanding accounting and taxation services to all our clients. The atmosphere he creates when greeting existing and new clients expounds the friendly, professional persona that our team has become renowned for.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/contact_submission.js.erb
$('.contact-submission-form form')[0].reset();
$('.contact-submisson').html("<%= @message %>");

app/views/home/index.html.erb
<%= render 'home/slider' %>
<%= render 'home/services' %>
<%= render 'home/counting' %>
<%= render 'home/clients' %>
<%= render 'home/expert' %>
<%= render 'home/client' %>

app/views/home/team.html.erb
<%= render 'home/team_banner' %>
<%= render 'home/team_main' %>

app/views/layouts/_footer.html.erb
<div class="spacer">

</div>
<footer class="footer-section" id='footer'>
  <div class="container">
    <div class="footer-part">
      <div class="row">
        <div class="col-sm-8 col-md-4">
          <div class="footer-wrapper">
            <span class="footer-logo">
              <%= link_to root_url do %>
                <%= image_tag 'logo-white.jpg', class: 'logo' %>
              <% end %>
            </span>
            <p class='text-center'>Taxation Services</p>
            <ul class="time-part text-center">
              <li><span>Mon - Fri</span>: 9am - 7pm</li>
            </ul>
          </div>
        </div>
        <div class="col-sm-4 col-md-4">
          <div class="footer-wrapper">
            <ul class="page-link">
              <li class="text-center <%= active_class(:index) %>">
                <%= link_to 'Home', root_url %>
              </li>
              <li class="text-center <%= active_class(:about) %>">
                <%= link_to 'About', about_url %>
              </li>
              <li class="text-center <%= active_class(:services) %>">
                <%= link_to 'Services', services_url %>
              </li>
              <li class="text-center <%= active_class(:team) %>">
                <%= link_to 'Team', team_url %>
              </li>
              <li class="text-center <%= active_class(:contact) %>">
                <%= link_to 'Contact', contact_url %>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-8 col-md-4">
          <div class="footer-wrapper">
            <ul class="social-media text-center">
               <li>
                    <%= link_to 'https://www.facebook.com/kalculators/', target:'_blank' do %>
                      <i class="fa fa-facebook" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to 'https://twitter.com/TheKalculators/', target:'_blank' do %>
                      <i class="fa fa-twitter" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                     <%= link_to 'https://www.linkedin.com/in/the-kalculators-126695144/', target:'_blank' do %>
                      <i class="fa fa-linkedin" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                     <%= link_to 'https://www.instagram.com/thekalculators/', target:'_blank' do %>
                      <i class="fa fa-instagram" aria-hidden="true"></i>
                    <% end %>
                  </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright-section text-center">
    <div class="container">
      <p class="inline-block">2017 © All rights reserved by
        <span>
          <%= link_to 'TheKalculators', root_url %>
        </span>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <header class="header-section">
    <div class="top-bar">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <%= link_to root_url do %>
              <%= image_tag 'logo-black.jpg', class: 'logo' %>
            <% end %>
          </div>
            <div class="col-md-6 col-md-offset-1 col-sm-6">
              <div class="header-left-bar text-right hidden-sm hidden-xs">
                <ul class="contact-wrapper">
                  <li><i class="fa fa-clock-o" aria-hidden="true"></i> Mon - Fri: 9 am - 7 pm</li>
                  <li><i class="fa fa-phone" aria-hidden="true"></i> 08 7480 2593</li>
                </ul>
              </div>
            </div>
            <div class="col-md-2 col-sm-12">
              <div class="header-right-bar hidden-sm hidden-xs">
                <ul class="social-icon">
                  <li>
                    <%= link_to 'https://www.facebook.com/kalculators/', target:'_blank' do %>
                      <i class="fa fa-facebook" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to 'https://twitter.com/TheKalculators/', target:'_blank' do %>
                      <i class="fa fa-twitter" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                     <%= link_to 'https://www.linkedin.com/in/the-kalculators-126695144/', target:'_blank' do %>
                      <i class="fa fa-linkedin" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                     <%= link_to 'https://www.instagram.com/thekalculators/', target:'_blank' do %>
                      <i class="fa fa-instagram" aria-hidden="true"></i>
                    <% end %>
                  </li>

                </ul>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="container">
      <nav class="navbar navbar-inverse hidden-sm hidden-xs">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li class='<%= active_class(:index) %>'>
                <%= link_to 'Home', root_url %>
              </li>
              <li class='<%= active_class(:about) %>'>
                <%= link_to 'About', about_url %>
              </li>
              <li class='<%= active_class(:services) %>'>
                <%= link_to 'Services', services_url %>
              </li>
              <li class='<%= active_class(:team) %>'>
                <%= link_to 'Team', team_url %>
              </li>
              <li class="mapdrop dropdown <%= active_class(:contact) %>">
                <%= link_to 'Contact', contact_url %>
                <ul class="map-menu">
                  <li>
                    <div class="author-details">
                      <h4>SALISBURY</h4>
                      <div class="item">
                        <div class="content">
                          <span class="number"><i class="fa fa-phone" aria-hidden="true"></i> 08 7480 2593</span>
                          <span class="message"><i class="fa fa-envelope" aria-hidden="true"></i> madeeha@thekalculators.com.au </span>
                        </div>
                      </div>
                    </div>
                    <div class="author-details">
                      <h4>BLAIR ATHOL</h4>
                      <div class="item">
                        <div class="content">
                          <span class="number"><i class="fa fa-phone" aria-hidden="true"></i> 08 7480 2593</span>
                          <span class="message"><i class="fa fa-envelope" aria-hidden="true"></i> kaleem@thekalculators.com.au</span>
                        </div>
                      </div>
                    </div>
                  <div class="author-details">
                      <h4>MURRAY BRIDGE</h4>
                      <div class="item">
                        <div class="content">
                          <span class="number"><i class="fa fa-phone" aria-hidden="true"></i> 08 7480 2593</span>
                          <span class="message"><i class="fa fa-envelope" aria-hidden="true"></i> hafiz@thekalculators.com.au</span>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="map-section pull-right">
                      <div id="menuMap"></div>
                    </div>
                  </li>
                </ul>
              </li>
          </ul>
          <ul class="access navbar-right">
            <li>
              <%= link_to 'Client Portal', 'https://cloud1.sagehandisoft.com.au/ClientPortal/Account/Login/', target:"_blank" %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalculators</title>
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>
  </head>
  <body id='top' class='about-page <%= custom_body_class %>'>
     <div id="preloader">
      <%= image_tag 'loader.gif' %>
    </div>
    <div id="main-wrapper">
      <%= render partial: 'layouts/header' %>
      <%= yield %>
     <%= render 'home/offcanvas' %>
     <%= render partial: 'home/overlay_footer' %>
    </div>
    <%= render partial: 'layouts/footer' %>
 </body>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2d0L5Q8cLifm_ZbUqkTjuF4onZ_RXPpM"></script>
</html>

app/views/locations/_contact.html.erb
<section class="contact-section google-map-contact-section">
  <div class="map-section">
    <div id="googleMap" class='google-map-contact'></div>
  </div>
  <div class="contact-section-one">
    <div class="container">
      <div class="section-one-wrapper">
          <div class="row">
              <h3>Contact our support guys or make appointment <br> with our consultants</h3>
              <div class="col-md-7 section-left">
                  <div class="contact-wrapper">
                    <p>Please contact us using the information below. For additional information on our services, please call at given numbers.</p>
                    <h4 class="contactheading salisbury-contactheading">SALISBURY</h4>
                    <%= render partial: 'locations/salisbury', locals: { footer: false } %>
                     <h4 class="contactheading">BLAIR ATHOL</h4>
                    <%= render partial: 'locations/prospect', locals: { footer: false } %>
                     <h4 class="contactheading">MURRAY BRIDGE</h4>
                    <%= render partial: 'locations/murray_bridge', locals: { footer: false } %>
                  </div>
              </div>
              <div class="col-md-5 contact-submission-form">
                  <div class='contact-submisson text-center'></div>
                  <div class="contact-wrapper">
                      <%= form_tag(contact_submission_path, method: :post, remote: true) do |f| %>
                      <form class="contact-form">
                          <div class="form-group">
                            <%= text_field_tag :name, '', id: 'inputName', class: 'form-control', placeholder: 'Name', required: true %>
                          </div>
                          <div class="form-group">
                            <%= email_field_tag :email, '', id: 'contactSearchBar', class: 'form-control', placeholder: 'Email' %>
                          </div>
                          <div class="form-group">
                            <%= text_area_tag :message, '', class: 'form-control', placeholder: 'Message', required: true %>
                          </div>
                          <div class="form-group">
                             <%= submit_tag 'Submit', class: 'subscribeBtn btn btn-primary' %>
                          </div>
                      <% end %>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>
</section>